name: FlixerProject
options:
  defaultConfig: Release
configs:
  Debug: debug
  Release: release
packages:
  swift-snapshot-testing:
    name: SnapshotTesting
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: '1.17.0'
  SwiftLint:
    url: https://github.com/realm/SwiftLint.git
    from: '0.55.1'
settings:
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
  CLANG_CXX_LANGUAGE_STANDARD: gnu++20
  ENABLE_USER_SCRIPT_SANDBOXING: 'YES'
  GCC_C_LANGUAGE_STANDARD: gnu17
  IPHONEOS_DEPLOYMENT_TARGET: '17.0'
  LOCALIZATION_PREFERS_STRING_CATALOGS: 'YES'
  MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
  MTL_FAST_MATH: 'YES'
  SDKROOT: iphoneos
  SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
  SWIFT_OPTIMIZATION_LEVEL: -Onone
schemes:
  FlixerProject:
    analyze:
      config: Debug
    archive:
      config: Debug
    build:
      targets:
        FlixerProject: all
    profile:
      config: Debug
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
      - FlixerProjectTests
      - FlixerProjectSnapshotTests
targets:
  FlixerProject:
    platform: iOS
    type: application
    settings:
      ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOL_FRAMEWORKS: SwiftUI
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: '1'
      DEVELOPMENT_ASSET_PATHS: '"FlixerProject/Preview Content"'
      DEVELOPMENT_TEAM: 34BX29F83H
      GENERATE_INFOPLIST_FILE: 'YES'
      INFOPLIST_KEY_CFBundleDisplayName: Flixer
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
      INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
      INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDarkContent
      INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
      MARKETING_VERSION: '1.0'
      PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProject
      SUPPORTED_PLATFORMS: iphoneos iphonesimulator
      SUPPORTS_MACCATALYST: 'NO'
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: 'YES'
      SWIFT_EMIT_LOC_STRINGS: 'YES'
      SWIFT_VERSION: '5.0'
      TARGETED_DEVICE_FAMILY: '1'
    buildToolPlugins:
      - plugin: SwiftLintBuildToolPlugin
        package: SwiftLint
    sources:
    - path: FlixerProject
      excludes:
      - FlixerProjectSnapshotTests
      - FlixerProjectTests
  FlixerProjectSnapshotTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      SWIFT_VERSION: '5.0'
      CODE_SIGN_STYLE: Automatic
      GENERATE_INFOPLIST_FILE: 'YES'
      PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProjectSnapshotTests
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 34BX29F83H
    dependencies:
    - target: FlixerProject
    - package: swift-snapshot-testing
      product: SnapshotTesting
    sources:
    - path: FlixerProjectSnapshotTests
  FlixerProjectTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      SWIFT_VERSION: '5.0'
      CODE_SIGN_STYLE: Automatic
      GENERATE_INFOPLIST_FILE: 'YES'
      PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProjectSnapshotTests
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 34BX29F83H
    dependencies:
    - target: FlixerProject
    sources:
    - name: FlixerProjectTests
      path: FlixerProjectTests
