name: FlixerProject
options:
  defaultConfig: Release
configs:
  Debug: debug
  Release: release
packages:
  swift-snapshot-testing:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: '1.17.0'
  SwiftLint:
    url: https://github.com/realm/SwiftLint.git
    from: '0.55.1'
schemes:
  FlixerProject:
    analyze:
      config: Debug
    archive:
      config: Debug
    build:
      targets:
        FlixerProject: all
    profile:
      config: Debug
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      testPlans:
        - path: FlixerProject/FlixerProject.xctestplan
          defaultPlan: true
      targets:
      - FlixerProjectTests
      - name: FlixerProjectSnapshotTests
        parallelizable: true
        randomExecutionOrder: true
targets:
  FlixerProject:
    platform: iOS
    type: application
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: '17.0'
    sources:
    - path: FlixerProject
  FlixerProjectSnapshotTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      SWIFT_VERSION: '5.0'
    dependencies:
    - target: FlixerProject
    sources:
    - name: Helpers
      path: FlixerProject/FlixerProjectSnapshotTests/Helpers
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/BaseComponents/Avatar/AvatarSnapshotTests.swift
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/BaseComponents/Icon/IconSnapshotTests.swift
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/BaseComponents/Text/TextSnapshopTest.swift
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/AgeRate/AgeRateSnapshotTests.swift
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/ImageFrame/ImageFrameSnapshotTests.swift
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/ProviderTag/ProviderTagSnapshotTests.swift
    - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/RatingBox/RatingBoxSnapshotTests.swift
  FlixerProjectTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      SWIFT_VERSION: '5.0'
    dependencies:
    - target: FlixerProject
    sources:
    - name: FlixerProjectTests
      path: FlixerProject/FlixerProjectTests

# attributes:
#   BuildIndependentTargetsInParallel: '1'
# configs:
#   Debug: debug
#   Release: release
# name: FlixerProject
# options:
#   defaultConfig: Release
#   groupSortPosition: top
#   transitivelyLinkDependencies: false
# schemes:
#   FlixerProject:
#     analyze:
#       config: Debug
#     archive:
#       config: Release
#     build:
#       targets:
#         FlixerProject:
#         - running
#         - testing
#         - profiling
#         - analyzing
#         - archiving
#     profile:
#       config: Release
#     run:
#       config: Debug
#     test:
#       config: Debug
#       targets:
#       - FlixerProjectTests
#       - name: FlixerProjectSnapshotTests
#         parallelizable: true
#         randomExecutionOrder: true
# settings:
#   configs:
#     Debug:
#       ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
#       CLANG_CXX_LANGUAGE_STANDARD: gnu++20
#       ENABLE_USER_SCRIPT_SANDBOXING: 'YES'
#       GCC_C_LANGUAGE_STANDARD: gnu17
#       IPHONEOS_DEPLOYMENT_TARGET: '17.0'
#       LOCALIZATION_PREFERS_STRING_CATALOGS: 'YES'
#       MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
#       MTL_FAST_MATH: 'YES'
#       SDKROOT: iphoneos
#       SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
#       SWIFT_OPTIMIZATION_LEVEL: -Onone
#     Release:
#       ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
#       CLANG_CXX_LANGUAGE_STANDARD: gnu++20
#       ENABLE_USER_SCRIPT_SANDBOXING: 'YES'
#       GCC_C_LANGUAGE_STANDARD: gnu17
#       IPHONEOS_DEPLOYMENT_TARGET: '17.0'
#       LOCALIZATION_PREFERS_STRING_CATALOGS: 'YES'
#       MTL_FAST_MATH: 'YES'
#       SDKROOT: iphoneos
#       SWIFT_COMPILATION_MODE: wholemodule
# targets:
#   FlixerProject:
#     platform: iOS
#     settings:
#       configs:
#         Debug:
#           ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOL_FRAMEWORKS: SwiftUI
#           ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
#           ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
#           CODE_SIGN_STYLE: Automatic
#           CURRENT_PROJECT_VERSION: '1'
#           DEVELOPMENT_ASSET_PATHS: '"FlixerProject/Preview Content"'
#           DEVELOPMENT_TEAM: 34BX29F83H
#           GENERATE_INFOPLIST_FILE: 'YES'
#           INFOPLIST_KEY_CFBundleDisplayName: Flixer
#           INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment
#           INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
#           INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
#           INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
#           INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDarkContent
#           INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
#           INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationLandscapeLeft
#             UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown
#           MARKETING_VERSION: '1.0'
#           PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProject
#           SUPPORTED_PLATFORMS: iphoneos iphonesimulator
#           SUPPORTS_MACCATALYST: 'NO'
#           SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: 'YES'
#           SWIFT_EMIT_LOC_STRINGS: 'YES'
#           SWIFT_VERSION: '5.0'
#           TARGETED_DEVICE_FAMILY: '1'
#         Release:
#           ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOL_FRAMEWORKS: SwiftUI
#           ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
#           ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
#           CODE_SIGN_STYLE: Automatic
#           CURRENT_PROJECT_VERSION: '1'
#           DEVELOPMENT_ASSET_PATHS: '"FlixerProject/Preview Content"'
#           DEVELOPMENT_TEAM: 34BX29F83H
#           GENERATE_INFOPLIST_FILE: 'YES'
#           INFOPLIST_KEY_CFBundleDisplayName: Flixer
#           INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment
#           INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
#           INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
#           INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
#           INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDarkContent
#           INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
#           INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationLandscapeLeft
#             UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown
#           MARKETING_VERSION: '1.0'
#           PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProject
#           SUPPORTED_PLATFORMS: iphoneos iphonesimulator
#           SUPPORTS_MACCATALYST: 'NO'
#           SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: 'YES'
#           SWIFT_EMIT_LOC_STRINGS: 'YES'
#           SWIFT_VERSION: '5.0'
#           TARGETED_DEVICE_FAMILY: '1'
#     sources:
#     - name: FlixerProject
#       path: FlixerProject
#     type: application
#   FlixerProjectSnapshotTests:
#     dependencies:
#     - target: FlixerProject
#     platform: iOS
#     settings:
#       configs:
#         Debug:
#           BUNDLE_LOADER: $(TEST_HOST)
#           CODE_SIGN_STYLE: Automatic
#           CURRENT_PROJECT_VERSION: '1'
#           DEVELOPMENT_TEAM: 34BX29F83H
#           GENERATE_INFOPLIST_FILE: 'YES'
#           MARKETING_VERSION: '1.0'
#           PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProjectSnapshotTests
#           SWIFT_EMIT_LOC_STRINGS: 'NO'
#           SWIFT_VERSION: '5.0'
#           TEST_HOST: $(BUILT_PRODUCTS_DIR)/FlixerProject.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FlixerProject
#         Release:
#           BUNDLE_LOADER: $(TEST_HOST)
#           CODE_SIGN_STYLE: Automatic
#           CURRENT_PROJECT_VERSION: '1'
#           DEVELOPMENT_TEAM: 34BX29F83H
#           GENERATE_INFOPLIST_FILE: 'YES'
#           MARKETING_VERSION: '1.0'
#           PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProjectSnapshotTests
#           SWIFT_EMIT_LOC_STRINGS: 'NO'
#           SWIFT_VERSION: '5.0'
#           TEST_HOST: $(BUILT_PRODUCTS_DIR)/FlixerProject.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FlixerProject
#     sources:
#     - name: Helpers
#       path: FlixerProject/FlixerProjectSnapshotTests/Helpers
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/BaseComponents/Avatar/AvatarSnapshotTests.swift
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/BaseComponents/Icon/IconSnapshotTests.swift
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/BaseComponents/Text/TextSnapshopTest.swift
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/AgeRate/AgeRateSnapshotTests.swift
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/ImageFrame/ImageFrameSnapshotTests.swift
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/ProviderTag/ProviderTagSnapshotTests.swift
#     - path: FlixerProject/FlixerProjectSnapshotTests/UI/Components/RatingBox/RatingBoxSnapshotTests.swift
#     type: bundle.unit-test
#   FlixerProjectTests:
#     dependencies:
#     - target: FlixerProject
#     platform: iOS
#     settings:
#       configs:
#         Debug:
#           ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
#           BUNDLE_LOADER: $(TEST_HOST)
#           CODE_SIGN_STYLE: Automatic
#           CURRENT_PROJECT_VERSION: '1'
#           DEVELOPMENT_TEAM: 34BX29F83H
#           GENERATE_INFOPLIST_FILE: 'YES'
#           IPHONEOS_DEPLOYMENT_TARGET: '17.0'
#           MARKETING_VERSION: '1.0'
#           PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProjectTests
#           SWIFT_EMIT_LOC_STRINGS: 'NO'
#           SWIFT_VERSION: '5.0'
#           TEST_HOST: $(BUILT_PRODUCTS_DIR)/FlixerProject.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FlixerProject
#         Release:
#           ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
#           BUNDLE_LOADER: $(TEST_HOST)
#           CODE_SIGN_STYLE: Automatic
#           CURRENT_PROJECT_VERSION: '1'
#           DEVELOPMENT_TEAM: 34BX29F83H
#           GENERATE_INFOPLIST_FILE: 'YES'
#           IPHONEOS_DEPLOYMENT_TARGET: '17.0'
#           MARKETING_VERSION: '1.0'
#           PRODUCT_BUNDLE_IDENTIFIER: com.coradine.FlixerProjectTests
#           SWIFT_EMIT_LOC_STRINGS: 'NO'
#           SWIFT_VERSION: '5.0'
#           TEST_HOST: $(BUILT_PRODUCTS_DIR)/FlixerProject.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FlixerProject
#     sources:
#     - name: FlixerProjectTests
#       path: FlixerProject/FlixerProjectTests
#     type: bundle.unit-test
