name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./FlixerProject
    env:
      scheme: FlixerProject
      device: iPhone 15
      platform: iOS Simulator
      ios_version: 17.5
      xcode_version: 15.4.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install yeetd
        run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &

      - name: Set Gems
        run: |
          gem install xcpretty
          brew install xcodegen

      - name: Generate Project
        run: xcodegen generate
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{env.xcode_version}}
        
      - name: Build
        run: |
          set -o pipefail
          xcodebuild build-for-testing \
          -scheme "$scheme" \
          -destination "platform=$platform,name=$device,OS=$ios_version" \
          -skipPackagePluginValidation \
          -skipMacroValidation | xcpretty

      - name: Test
        run: |
          set -o pipefail
          xcodebuild test-without-building \
          -scheme "$scheme" \
          -destination "platform=$platform,name=$device,OS=$ios_version" \
          -skipPackagePluginValidation \
          -skipMacroValidation | xcpretty
